---
## add user ofr ovirt

- hosts: virtmanager
  vars:
    user_name: user1
    password: qwer1234
  tasks:
    - name: add user for ovirt
      shell: ovirt-aaa-jdbc-tool user add {{ user_name }}
      ignore_errors: True

    - name: add password
      shell: ovirt-aaa-jdbc-tool user password-reset {{ user_name }} --password=pass:{{ password }}
